// Generated from shared/profile-platforms.json by scripts/generate-profile-platforms.mjs.
// Do not edit; artwork and recognition metadata are maintained in the source catalog.

class ProfilePlatformMatch {
  const ProfilePlatformMatch({required this.host, required this.pathPrefix, required this.subdomains});
  final String host;
  final String pathPrefix;
  final bool subdomains;
}

class ProfilePlatformArtwork {
  const ProfilePlatformArtwork({required this.file, required this.sourceWidth, required this.sourceHeight, required this.left, required this.top, required this.width, required this.height});
  final String file;
  final double sourceWidth;
  final double sourceHeight;
  final double left;
  final double top;
  final double width;
  final double height;
}

class ProfilePlatformDefinition {
  const ProfilePlatformDefinition({required this.id, required this.name, required this.category, required this.aliases, required this.regions, required this.domains, required this.matches, required this.sampleUrl, required this.asset});
  final String id;
  final String name;
  final String category;
  final List<String> aliases;
  final List<String> regions;
  final List<String> domains;
  final List<ProfilePlatformMatch> matches;
  final String sampleUrl;
  final ProfilePlatformArtwork asset;
}

const profilePlatformCatalog = <ProfilePlatformDefinition>[
  ProfilePlatformDefinition(
    id: 'youtube',
    name: 'YouTube',
    category: 'video',
    aliases: ['ยูทูบ'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['youtube.com', 'youtu.be'],
    matches: [],
    sampleUrl: 'https://youtu.be/video',
    asset: ProfilePlatformArtwork(
      file: 'youtube.png',
      sourceWidth: 1255.0,
      sourceHeight: 1075.0,
      left: 214.0,
      top: 248.0,
      width: 827.0,
      height: 579.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'shopee',
    name: 'Shopee',
    category: 'shopping',
    aliases: ['ช้อปปี้'],
    regions: ['Southeast Asia', 'เอเชียตะวันออกเฉียงใต้', 'Brazil', 'บราซิล'],
    domains: ['shopee.co.th', 'shopee.com', 'shope.ee'],
    matches: [],
    sampleUrl: 'https://shopee.co.th/shop',
    asset: ProfilePlatformArtwork(
      file: 'shopee.png',
      sourceWidth: 96.0,
      sourceHeight: 96.0,
      left: 5.0,
      top: 0.0,
      width: 86.0,
      height: 96.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'lazada',
    name: 'Lazada',
    category: 'shopping',
    aliases: ['ลาซาด้า'],
    regions: ['Southeast Asia', 'เอเชียตะวันออกเฉียงใต้'],
    domains: ['lazada.co.th', 'lazada.com'],
    matches: [],
    sampleUrl: 'https://lazada.co.th/shop',
    asset: ProfilePlatformArtwork(
      file: 'lazada.png',
      sourceWidth: 128.0,
      sourceHeight: 128.0,
      left: 0.0,
      top: 0.0,
      width: 128.0,
      height: 128.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'line',
    name: 'LINE',
    category: 'messaging',
    aliases: ['ไลน์'],
    regions: ['Japan', 'ญี่ปุ่น', 'Thailand', 'ไทย', 'Taiwan', 'ไต้หวัน'],
    domains: ['line.me', 'lin.ee'],
    matches: [],
    sampleUrl: 'https://lin.ee/shop',
    asset: ProfilePlatformArtwork(
      file: 'line.png',
      sourceWidth: 1001.0,
      sourceHeight: 1000.0,
      left: 0.0,
      top: 0.0,
      width: 1001.0,
      height: 1000.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'tiktok',
    name: 'TikTok',
    category: 'video',
    aliases: ['ติ๊กต็อก'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['tiktok.com'],
    matches: [],
    sampleUrl: 'https://www.tiktok.com/@shop',
    asset: ProfilePlatformArtwork(
      file: 'tiktok.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'instagram',
    name: 'Instagram',
    category: 'social',
    aliases: ['อินสตาแกรม', 'ไอจี', 'IG'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['instagram.com'],
    matches: [],
    sampleUrl: 'https://www.instagram.com/shop',
    asset: ProfilePlatformArtwork(
      file: 'instagram.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'facebook',
    name: 'Facebook',
    category: 'social',
    aliases: ['เฟซบุ๊ก', 'FB'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['facebook.com', 'fb.com', 'fb.me'],
    matches: [],
    sampleUrl: 'https://www.facebook.com/shop',
    asset: ProfilePlatformArtwork(
      file: 'facebook.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'messenger',
    name: 'Messenger',
    category: 'messaging',
    aliases: ['เมสเซนเจอร์'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['m.me', 'messenger.com'],
    matches: [ProfilePlatformMatch(host: 'facebook.com', pathPrefix: '/messages', subdomains: true)],
    sampleUrl: 'https://m.me/shop',
    asset: ProfilePlatformArtwork(
      file: 'messenger.png',
      sourceWidth: 128.0,
      sourceHeight: 128.0,
      left: 5.0,
      top: 7.0,
      width: 117.0,
      height: 116.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'whatsapp',
    name: 'WhatsApp',
    category: 'messaging',
    aliases: ['วอตส์แอป', 'วอทส์แอป'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['wa.me', 'whatsapp.com'],
    matches: [],
    sampleUrl: 'https://wa.me/66812345678',
    asset: ProfilePlatformArtwork(
      file: 'whatsapp.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'google_maps',
    name: 'Google Maps',
    category: 'travel',
    aliases: ['กูเกิลแมป', 'แผนที่'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['maps.app.goo.gl', 'maps.google.com', 'maps.google.co.th'],
    matches: [ProfilePlatformMatch(host: 'google.com', pathPrefix: '/maps', subdomains: false), ProfilePlatformMatch(host: 'www.google.com', pathPrefix: '/maps', subdomains: false), ProfilePlatformMatch(host: 'google.co.th', pathPrefix: '/maps', subdomains: false), ProfilePlatformMatch(host: 'www.google.co.th', pathPrefix: '/maps', subdomains: false), ProfilePlatformMatch(host: 'goo.gl', pathPrefix: '/maps', subdomains: false)],
    sampleUrl: 'https://maps.app.goo.gl/shop',
    asset: ProfilePlatformArtwork(
      file: 'google_maps.png',
      sourceWidth: 192.0,
      sourceHeight: 192.0,
      left: 27.0,
      top: 8.0,
      width: 138.0,
      height: 176.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'wechat',
    name: 'WeChat',
    category: 'messaging',
    aliases: ['วีแชท', 'Weixin', 'เว่ยซิน', '微信'],
    regions: ['China', 'จีน', '中国'],
    domains: ['wechat.com', 'weixin.qq.com'],
    matches: [],
    sampleUrl: 'https://wechat.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'wechat.png',
      sourceWidth: 512.0,
      sourceHeight: 512.0,
      left: 0.0,
      top: 0.0,
      width: 512.0,
      height: 512.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'qq',
    name: 'QQ',
    category: 'messaging',
    aliases: ['คิวคิว', 'Tencent QQ', '腾讯QQ'],
    regions: ['China', 'จีน', '中国'],
    domains: ['im.qq.com', 'qm.qq.com'],
    matches: [],
    sampleUrl: 'https://im.qq.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'qq.png',
      sourceWidth: 62.0,
      sourceHeight: 62.0,
      left: 7.0,
      top: 2.0,
      width: 49.0,
      height: 58.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'weibo',
    name: 'Weibo',
    category: 'social',
    aliases: ['เว่ยป๋อ', 'Sina Weibo', '微博'],
    regions: ['China', 'จีน', '中国'],
    domains: ['weibo.com', 'weibo.cn'],
    matches: [],
    sampleUrl: 'https://weibo.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'weibo.png',
      sourceWidth: 512.0,
      sourceHeight: 512.0,
      left: 0.0,
      top: 0.0,
      width: 512.0,
      height: 512.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'douyin',
    name: 'Douyin',
    category: 'video',
    aliases: ['โต่วอิน', '抖音'],
    regions: ['China', 'จีน', '中国'],
    domains: ['douyin.com', 'iesdouyin.com'],
    matches: [],
    sampleUrl: 'https://douyin.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'douyin.png',
      sourceWidth: 108.0,
      sourceHeight: 108.0,
      left: 0.0,
      top: 0.0,
      width: 108.0,
      height: 108.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'bilibili',
    name: 'Bilibili',
    category: 'video',
    aliases: ['บิลิบิลิ', '哔哩哔哩', 'B站'],
    regions: ['China', 'จีน', '中国'],
    domains: ['bilibili.com', 'b23.tv'],
    matches: [],
    sampleUrl: 'https://bilibili.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'bilibili.png',
      sourceWidth: 512.0,
      sourceHeight: 512.0,
      left: 0.0,
      top: 0.0,
      width: 512.0,
      height: 512.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'xiaohongshu',
    name: 'Xiaohongshu',
    category: 'social',
    aliases: ['เสี่ยวหงชู', 'REDnote', 'Rednote', '小红书'],
    regions: ['China', 'จีน', '中国'],
    domains: ['xiaohongshu.com', 'xhslink.com'],
    matches: [],
    sampleUrl: 'https://xiaohongshu.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'xiaohongshu.png',
      sourceWidth: 180.0,
      sourceHeight: 180.0,
      left: 0.0,
      top: 0.0,
      width: 180.0,
      height: 180.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'kuaishou',
    name: 'Kuaishou',
    category: 'video',
    aliases: ['ไควโช่ว', '快手'],
    regions: ['China', 'จีน', '中国'],
    domains: ['kuaishou.com', 'gifshow.com'],
    matches: [],
    sampleUrl: 'https://kuaishou.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'kuaishou.png',
      sourceWidth: 512.0,
      sourceHeight: 512.0,
      left: 0.0,
      top: 0.0,
      width: 512.0,
      height: 512.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'taobao',
    name: 'Taobao',
    category: 'shopping',
    aliases: ['เถาเป่า', '淘宝'],
    regions: ['China', 'จีน', '中国'],
    domains: ['taobao.com', 'e.tb.cn', 'm.tb.cn'],
    matches: [],
    sampleUrl: 'https://taobao.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'taobao.png',
      sourceWidth: 114.0,
      sourceHeight: 114.0,
      left: 0.0,
      top: 0.0,
      width: 114.0,
      height: 114.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'tmall',
    name: 'Tmall',
    category: 'shopping',
    aliases: ['ทีมอลล์', '天猫'],
    regions: ['China', 'จีน', '中国'],
    domains: ['tmall.com'],
    matches: [],
    sampleUrl: 'https://tmall.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'tmall.png',
      sourceWidth: 512.0,
      sourceHeight: 512.0,
      left: 0.0,
      top: 0.0,
      width: 512.0,
      height: 512.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'jd',
    name: 'JD.com',
    category: 'shopping',
    aliases: ['จิงตง', 'Jingdong', '京东'],
    regions: ['China', 'จีน', '中国'],
    domains: ['jd.com', '3.cn'],
    matches: [],
    sampleUrl: 'https://jd.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'jd.png',
      sourceWidth: 96.0,
      sourceHeight: 96.0,
      left: 0.0,
      top: 0.0,
      width: 96.0,
      height: 96.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'pinduoduo',
    name: 'Pinduoduo',
    category: 'shopping',
    aliases: ['พินตัวตัว', '拼多多'],
    regions: ['China', 'จีน', '中国'],
    domains: ['pinduoduo.com', 'yangkeduo.com'],
    matches: [],
    sampleUrl: 'https://pinduoduo.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'pinduoduo.png',
      sourceWidth: 48.0,
      sourceHeight: 48.0,
      left: 0.0,
      top: 0.0,
      width: 48.0,
      height: 48.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'alipay',
    name: 'Alipay',
    category: 'payments',
    aliases: ['อาลีเพย์', '支付宝'],
    regions: ['China', 'จีน', '中国'],
    domains: ['alipay.com'],
    matches: [],
    sampleUrl: 'https://alipay.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'alipay.png',
      sourceWidth: 2600.0,
      sourceHeight: 1950.0,
      left: 1034.0,
      top: 749.0,
      width: 531.0,
      height: 452.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'baidu',
    name: 'Baidu',
    category: 'tools',
    aliases: ['ไป่ตู้', '百度'],
    regions: ['China', 'จีน', '中国'],
    domains: ['baidu.com'],
    matches: [],
    sampleUrl: 'https://baidu.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'baidu.png',
      sourceWidth: 1024.0,
      sourceHeight: 1024.0,
      left: 0.0,
      top: 0.0,
      width: 1024.0,
      height: 1024.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'zhihu',
    name: 'Zhihu',
    category: 'social',
    aliases: ['จือหู', '知乎'],
    regions: ['China', 'จีน', '中国'],
    domains: ['zhihu.com'],
    matches: [],
    sampleUrl: 'https://zhihu.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'zhihu.png',
      sourceWidth: 152.0,
      sourceHeight: 152.0,
      left: 0.0,
      top: 0.0,
      width: 152.0,
      height: 152.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'douban',
    name: 'Douban',
    category: 'social',
    aliases: ['โต้วป้าน', '豆瓣'],
    regions: ['China', 'จีน', '中国'],
    domains: ['douban.com', 'douban.fm'],
    matches: [],
    sampleUrl: 'https://douban.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'douban.png',
      sourceWidth: 512.0,
      sourceHeight: 512.0,
      left: 0.0,
      top: 0.0,
      width: 512.0,
      height: 512.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'youku',
    name: 'Youku',
    category: 'video',
    aliases: ['โยวคู่', '优酷'],
    regions: ['China', 'จีน', '中国'],
    domains: ['youku.com'],
    matches: [],
    sampleUrl: 'https://youku.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'youku.png',
      sourceWidth: 195.0,
      sourceHeight: 195.0,
      left: 39.0,
      top: 29.0,
      width: 118.0,
      height: 137.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'dingtalk',
    name: 'DingTalk',
    category: 'messaging',
    aliases: ['ติงทอล์ก', '钉钉'],
    regions: ['China', 'จีน', '中国'],
    domains: ['dingtalk.com'],
    matches: [],
    sampleUrl: 'https://dingtalk.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'dingtalk.png',
      sourceWidth: 444.0,
      sourceHeight: 444.0,
      left: 0.0,
      top: 0.0,
      width: 444.0,
      height: 444.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'netease_music',
    name: 'NetEase Cloud Music',
    category: 'music',
    aliases: ['เน็ตอีส', 'NetEase', 'Cloud Music', '网易云音乐'],
    regions: ['China', 'จีน', '中国'],
    domains: ['music.163.com'],
    matches: [],
    sampleUrl: 'https://music.163.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'netease_music.png',
      sourceWidth: 512.0,
      sourceHeight: 512.0,
      left: 0.0,
      top: 0.0,
      width: 512.0,
      height: 512.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'meituan',
    name: 'Meituan',
    category: 'shopping',
    aliases: ['เหมยถวน', '美团'],
    regions: ['China', 'จีน', '中国'],
    domains: ['meituan.com'],
    matches: [],
    sampleUrl: 'https://meituan.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'meituan.png',
      sourceWidth: 48.0,
      sourceHeight: 48.0,
      left: 0.0,
      top: 0.0,
      width: 48.0,
      height: 48.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'eleme',
    name: 'Taobao Instant Commerce',
    category: 'shopping',
    aliases: ['Ele.me', '饿了么', '淘宝闪购', 'เอเลมี', 'Taobao Instant Commerce'],
    regions: ['China', 'จีน', '中国'],
    domains: ['ele.me'],
    matches: [],
    sampleUrl: 'https://ele.me/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'eleme.png',
      sourceWidth: 96.0,
      sourceHeight: 96.0,
      left: 0.0,
      top: 0.0,
      width: 96.0,
      height: 96.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'trip_com',
    name: 'Trip.com',
    category: 'travel',
    aliases: ['ทริปดอทคอม', 'Trip', 'Trip.com'],
    regions: ['China/Global', 'จีน', 'China', 'สิงคโปร์', 'Singapore', 'ทั่วโลก', 'Global'],
    domains: ['trip.com'],
    matches: [],
    sampleUrl: 'https://trip.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'trip_com.png',
      sourceWidth: 512.0,
      sourceHeight: 512.0,
      left: 0.0,
      top: 0.0,
      width: 512.0,
      height: 512.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'kakao_talk',
    name: 'KakaoTalk',
    category: 'messaging',
    aliases: ['กาเกาทอล์ก', 'คา카오ทอล์ก', 'Kakao', '카카오톡'],
    regions: ['Korea', 'เกาหลี', 'เกาหลีใต้', 'South Korea', '한국'],
    domains: ['open.kakao.com', 'pf.kakao.com', 'talk.kakao.com'],
    matches: [],
    sampleUrl: 'https://open.kakao.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'kakao_talk.png',
      sourceWidth: 216.0,
      sourceHeight: 216.0,
      left: 0.0,
      top: 0.0,
      width: 216.0,
      height: 216.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'naver',
    name: 'NAVER',
    category: 'tools',
    aliases: ['เนเวอร์', '네이버'],
    regions: ['Korea', 'เกาหลี', 'เกาหลีใต้', 'South Korea', '한국'],
    domains: ['naver.com', 'naver.me'],
    matches: [],
    sampleUrl: 'https://naver.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'naver.png',
      sourceWidth: 96.0,
      sourceHeight: 96.0,
      left: 0.0,
      top: 0.0,
      width: 96.0,
      height: 96.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'coupang',
    name: 'Coupang',
    category: 'shopping',
    aliases: ['คูปัง', '쿠팡'],
    regions: ['Korea', 'เกาหลี', 'เกาหลีใต้', 'South Korea', '한국', 'ไต้หวัน', 'Taiwan'],
    domains: ['coupang.com', 'coupang.link'],
    matches: [],
    sampleUrl: 'https://coupang.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'coupang.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'band',
    name: 'BAND',
    category: 'social',
    aliases: ['แบนด์', '밴드'],
    regions: ['Korea/Global', 'เกาหลี', 'เกาหลีใต้', 'Korea', 'South Korea', '한국'],
    domains: ['band.us'],
    matches: [],
    sampleUrl: 'https://band.us/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'band.png',
      sourceWidth: 96.0,
      sourceHeight: 96.0,
      left: 0.0,
      top: 0.0,
      width: 96.0,
      height: 96.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'rakuten',
    name: 'Rakuten',
    category: 'shopping',
    aliases: ['ราคุเทน', '楽天'],
    regions: ['Japan', 'ญี่ปุ่น', '日本'],
    domains: ['rakuten.co.jp', 'rakuten.com', 'rakuten.net'],
    matches: [],
    sampleUrl: 'https://rakuten.co.jp/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'rakuten.png',
      sourceWidth: 64.0,
      sourceHeight: 64.0,
      left: 11.0,
      top: 7.0,
      width: 48.0,
      height: 51.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'mercari',
    name: 'Mercari',
    category: 'shopping',
    aliases: ['เมอร์คาริ', 'เมลคาริ', 'メルカリ'],
    regions: ['Japan/US', 'ญี่ปุ่น', 'Japan', '日本', 'สหรัฐ', 'USA', 'US'],
    domains: ['mercari.com', 'mercari.jp'],
    matches: [],
    sampleUrl: 'https://mercari.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'mercari.png',
      sourceWidth: 512.0,
      sourceHeight: 512.0,
      left: 0.0,
      top: 0.0,
      width: 512.0,
      height: 512.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'yahoo_japan',
    name: 'Yahoo! Japan',
    category: 'tools',
    aliases: ['ยาฮูญี่ปุ่น', 'Yahoo Japan', 'Yahoo! Japan', 'ヤフー'],
    regions: ['Japan', 'ญี่ปุ่น', '日本'],
    domains: ['yahoo.co.jp'],
    matches: [],
    sampleUrl: 'https://yahoo.co.jp/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'yahoo_japan.png',
      sourceWidth: 120.0,
      sourceHeight: 120.0,
      left: 0.0,
      top: 0.0,
      width: 120.0,
      height: 120.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'paypay',
    name: 'PayPay',
    category: 'payments',
    aliases: ['เพย์เพย์', 'ペイペイ'],
    regions: ['Japan', 'ญี่ปุ่น', '日本'],
    domains: ['paypay.ne.jp'],
    matches: [],
    sampleUrl: 'https://paypay.ne.jp/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'paypay.png',
      sourceWidth: 180.0,
      sourceHeight: 180.0,
      left: 0.0,
      top: 0.0,
      width: 180.0,
      height: 180.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'niconico',
    name: 'Niconico',
    category: 'video',
    aliases: ['นิโคนิโค', 'NicoNico', 'ニコニコ'],
    regions: ['Japan', 'ญี่ปุ่น', '日本'],
    domains: ['nicovideo.jp', 'nico.ms'],
    matches: [],
    sampleUrl: 'https://nicovideo.jp/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'niconico.png',
      sourceWidth: 144.0,
      sourceHeight: 144.0,
      left: 2.0,
      top: 2.0,
      width: 140.0,
      height: 140.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'pixiv',
    name: 'pixiv',
    category: 'creator',
    aliases: ['พิกซิฟ', 'พิกซิฟว์', 'ピクシブ'],
    regions: ['Japan/Global', 'ญี่ปุ่น', 'Japan', '日本'],
    domains: ['pixiv.net', 'pixiv.me'],
    matches: [],
    sampleUrl: 'https://pixiv.net/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'pixiv.png',
      sourceWidth: 180.0,
      sourceHeight: 180.0,
      left: 0.0,
      top: 0.0,
      width: 180.0,
      height: 180.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'sharechat',
    name: 'ShareChat',
    category: 'social',
    aliases: ['แชร์แชท', 'शेयरचैट'],
    regions: ['India', 'อินเดีย', 'भारत'],
    domains: ['sharechat.com'],
    matches: [],
    sampleUrl: 'https://sharechat.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'sharechat.png',
      sourceWidth: 96.0,
      sourceHeight: 96.0,
      left: 0.0,
      top: 0.0,
      width: 96.0,
      height: 96.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'moj',
    name: 'Moj',
    category: 'video',
    aliases: ['โมจ', 'मोज'],
    regions: ['India', 'อินเดีย', 'भारत'],
    domains: ['mojapp.in'],
    matches: [],
    sampleUrl: 'https://mojapp.in/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'moj.png',
      sourceWidth: 96.0,
      sourceHeight: 96.0,
      left: 0.0,
      top: 0.0,
      width: 96.0,
      height: 96.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'flipkart',
    name: 'Flipkart',
    category: 'shopping',
    aliases: ['ฟลิปคาร์ต', 'फ्लिपकार्ट'],
    regions: ['India', 'อินเดีย', 'भारत'],
    domains: ['flipkart.com', 'fkrt.it'],
    matches: [],
    sampleUrl: 'https://flipkart.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'flipkart.png',
      sourceWidth: 512.0,
      sourceHeight: 512.0,
      left: 0.0,
      top: 0.0,
      width: 512.0,
      height: 512.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'meesho',
    name: 'Meesho',
    category: 'shopping',
    aliases: ['มีโช', 'मीशो'],
    regions: ['India', 'อินเดีย', 'भारत'],
    domains: ['meesho.com'],
    matches: [],
    sampleUrl: 'https://meesho.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'meesho.png',
      sourceWidth: 1080.0,
      sourceHeight: 1080.0,
      left: 0.0,
      top: 0.0,
      width: 1080.0,
      height: 1080.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'zalo',
    name: 'Zalo',
    category: 'messaging',
    aliases: ['ซาโล', 'ซาโล่'],
    regions: ['Vietnam', 'เวียดนาม', 'Việt Nam'],
    domains: ['zalo.me', 'zaloapp.com', 'chat.zalo.me'],
    matches: [],
    sampleUrl: 'https://zalo.me/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'zalo.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'tokopedia',
    name: 'Tokopedia',
    category: 'shopping',
    aliases: ['โทโคพีเดีย', 'Tokped'],
    regions: ['Indonesia', 'อินโดนีเซีย'],
    domains: ['tokopedia.com', 'tokopedia.link'],
    matches: [],
    sampleUrl: 'https://tokopedia.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'tokopedia.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'tiki',
    name: 'Tiki',
    category: 'shopping',
    aliases: ['ติกิ'],
    regions: ['Vietnam', 'เวียดนาม', 'Việt Nam'],
    domains: ['tiki.vn'],
    matches: [],
    sampleUrl: 'https://tiki.vn/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'tiki.png',
      sourceWidth: 48.0,
      sourceHeight: 48.0,
      left: 0.0,
      top: 0.0,
      width: 48.0,
      height: 48.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'traveloka',
    name: 'Traveloka',
    category: 'travel',
    aliases: ['ทราเวลโลก้า', 'ทราเวลโลกา'],
    regions: ['SEA', 'อินโดนีเซีย', 'Indonesia', 'เอเชียตะวันออกเฉียงใต้', 'Southeast Asia'],
    domains: ['traveloka.com'],
    matches: [],
    sampleUrl: 'https://traveloka.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'traveloka.png',
      sourceWidth: 48.0,
      sourceHeight: 48.0,
      left: 0.0,
      top: 3.0,
      width: 48.0,
      height: 40.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'grab',
    name: 'Grab',
    category: 'travel',
    aliases: ['แกร็บ', 'GrabFood'],
    regions: ['SEA', 'ไทย', 'Thailand', 'สิงคโปร์', 'Singapore', 'เอเชียตะวันออกเฉียงใต้', 'Southeast Asia'],
    domains: ['grab.com', 'grab.onelink.me', 'grb.to'],
    matches: [],
    sampleUrl: 'https://grab.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'grab.png',
      sourceWidth: 96.0,
      sourceHeight: 96.0,
      left: 0.0,
      top: 0.0,
      width: 96.0,
      height: 96.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'gojek',
    name: 'Gojek',
    category: 'travel',
    aliases: ['โกเจ็ก', 'Go-Jek', 'GoFood'],
    regions: ['Indonesia', 'อินโดนีเซีย', 'สิงคโปร์', 'Singapore'],
    domains: ['gojek.com'],
    matches: [],
    sampleUrl: 'https://gojek.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'gojek.png',
      sourceWidth: 512.0,
      sourceHeight: 512.0,
      left: 0.0,
      top: 0.0,
      width: 512.0,
      height: 512.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'carousell',
    name: 'Carousell',
    category: 'shopping',
    aliases: ['คารูเซล', 'คารูเซลล์'],
    regions: ['SEA', 'สิงคโปร์', 'Singapore', 'เอเชียตะวันออกเฉียงใต้', 'Southeast Asia'],
    domains: ['carousell.com', 'carousell.sg', 'carousell.com.my', 'carousell.ph', 'carousell.com.hk', 'carousell.com.tw'],
    matches: [],
    sampleUrl: 'https://carousell.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'carousell.png',
      sourceWidth: 100.0,
      sourceHeight: 100.0,
      left: 8.0,
      top: 5.0,
      width: 84.0,
      height: 90.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'daraz',
    name: 'Daraz',
    category: 'shopping',
    aliases: ['ดาราซ', 'ดาราซ์'],
    regions: ['South Asia', 'ปากีสถาน', 'Pakistan', 'บังกลาเทศ', 'Bangladesh', 'ศรีลังกา', 'Sri Lanka', 'เนปาล', 'Nepal', 'เอเชียใต้'],
    domains: ['daraz.pk', 'daraz.com.bd', 'daraz.lk', 'daraz.com.np'],
    matches: [],
    sampleUrl: 'https://daraz.pk/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'daraz.png',
      sourceWidth: 64.0,
      sourceHeight: 64.0,
      left: 16.0,
      top: 5.0,
      width: 32.0,
      height: 54.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'x',
    name: 'X',
    category: 'social',
    aliases: ['Twitter', 'ทวิตเตอร์', 'เอ็กซ์'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['x.com', 'twitter.com'],
    matches: [],
    sampleUrl: 'https://x.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'x.png',
      sourceWidth: 1024.0,
      sourceHeight: 1024.0,
      left: 0.0,
      top: 0.0,
      width: 1024.0,
      height: 1024.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'threads',
    name: 'Threads',
    category: 'social',
    aliases: ['เธรดส์'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['threads.com', 'threads.net'],
    matches: [],
    sampleUrl: 'https://threads.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'threads.png',
      sourceWidth: 256.0,
      sourceHeight: 256.0,
      left: 0.0,
      top: 0.0,
      width: 256.0,
      height: 256.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'bluesky',
    name: 'Bluesky',
    category: 'social',
    aliases: ['บลูสกาย'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['bsky.app', 'bsky.social'],
    matches: [],
    sampleUrl: 'https://bsky.app/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'bluesky.png',
      sourceWidth: 1136.0,
      sourceHeight: 1001.0,
      left: 0.0,
      top: 0.0,
      width: 1136.0,
      height: 1001.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'mastodon',
    name: 'Mastodon',
    category: 'social',
    aliases: ['มาสโตดอน'],
    regions: ['Global', 'ทั่วโลก', 'Europe', 'ยุโรป'],
    domains: ['mastodon.social', 'joinmastodon.org'],
    matches: [],
    sampleUrl: 'https://mastodon.social/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'mastodon.png',
      sourceWidth: 228.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 226.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'snapchat',
    name: 'Snapchat',
    category: 'social',
    aliases: ['สแนปแชต'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['snapchat.com'],
    matches: [],
    sampleUrl: 'https://snapchat.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'snapchat.png',
      sourceWidth: 192.0,
      sourceHeight: 192.0,
      left: 0.0,
      top: 0.0,
      width: 192.0,
      height: 192.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'pinterest',
    name: 'Pinterest',
    category: 'social',
    aliases: ['พินเทอเรสต์'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['pinterest.com', 'pin.it'],
    matches: [],
    sampleUrl: 'https://pinterest.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'pinterest.png',
      sourceWidth: 144.0,
      sourceHeight: 144.0,
      left: 20.0,
      top: 20.0,
      width: 104.0,
      height: 104.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'linkedin',
    name: 'LinkedIn',
    category: 'social',
    aliases: ['ลิงก์อิน'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['linkedin.com', 'lnkd.in'],
    matches: [],
    sampleUrl: 'https://linkedin.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'linkedin.png',
      sourceWidth: 635.0,
      sourceHeight: 540.0,
      left: 0.0,
      top: 0.0,
      width: 635.0,
      height: 540.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'reddit',
    name: 'Reddit',
    category: 'social',
    aliases: ['เรดดิต'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['reddit.com', 'redd.it'],
    matches: [],
    sampleUrl: 'https://reddit.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'reddit.png',
      sourceWidth: 48.0,
      sourceHeight: 48.0,
      left: 0.0,
      top: 0.0,
      width: 48.0,
      height: 48.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'telegram',
    name: 'Telegram',
    category: 'messaging',
    aliases: ['เทเลแกรม'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['telegram.org', 't.me'],
    matches: [],
    sampleUrl: 'https://telegram.org/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'telegram.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'signal',
    name: 'Signal',
    category: 'messaging',
    aliases: ['ซิกแนล'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['signal.org', 'signal.me'],
    matches: [],
    sampleUrl: 'https://signal.org/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'signal.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'viber',
    name: 'Viber',
    category: 'messaging',
    aliases: ['ไวเบอร์'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['viber.com'],
    matches: [],
    sampleUrl: 'https://viber.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'viber.png',
      sourceWidth: 192.0,
      sourceHeight: 192.0,
      left: 6.0,
      top: 0.0,
      width: 180.0,
      height: 192.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'discord',
    name: 'Discord',
    category: 'messaging',
    aliases: ['ดิสคอร์ด'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['discord.com', 'discord.gg'],
    matches: [],
    sampleUrl: 'https://discord.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'discord.png',
      sourceWidth: 240.0,
      sourceHeight: 182.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 182.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'twitch',
    name: 'Twitch',
    category: 'video',
    aliases: ['ทวิช'],
    regions: ['Global', 'ทั่วโลก', 'US', 'United States', 'สหรัฐอเมริกา'],
    domains: ['twitch.tv'],
    matches: [],
    sampleUrl: 'https://twitch.tv/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'twitch.png',
      sourceWidth: 206.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 206.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'kick',
    name: 'Kick',
    category: 'video',
    aliases: ['คิก'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['kick.com'],
    matches: [],
    sampleUrl: 'https://kick.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'kick.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 9.0,
      top: 0.0,
      width: 215.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'spotify',
    name: 'Spotify',
    category: 'music',
    aliases: ['สปอติฟาย'],
    regions: ['Global', 'ทั่วโลก', 'Sweden', 'สวีเดน'],
    domains: ['spotify.com', 'spoti.fi'],
    matches: [],
    sampleUrl: 'https://spotify.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'spotify.png',
      sourceWidth: 240.0,
      sourceHeight: 229.0,
      left: 8.0,
      top: 3.0,
      width: 224.0,
      height: 223.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'apple_music',
    name: 'Apple Music',
    category: 'music',
    aliases: ['แอปเปิลมิวสิก'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['music.apple.com'],
    matches: [],
    sampleUrl: 'https://music.apple.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'apple_music.png',
      sourceWidth: 180.0,
      sourceHeight: 180.0,
      left: 0.0,
      top: 0.0,
      width: 180.0,
      height: 180.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'soundcloud',
    name: 'SoundCloud',
    category: 'music',
    aliases: ['ซาวด์คลาวด์'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['soundcloud.com'],
    matches: [],
    sampleUrl: 'https://soundcloud.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'soundcloud.png',
      sourceWidth: 114.0,
      sourceHeight: 114.0,
      left: 0.0,
      top: 0.0,
      width: 114.0,
      height: 114.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'bandcamp',
    name: 'Bandcamp',
    category: 'music',
    aliases: ['แบนด์แคมป์'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['bandcamp.com'],
    matches: [],
    sampleUrl: 'https://bandcamp.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'bandcamp.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 49.0,
      width: 240.0,
      height: 142.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'deezer',
    name: 'Deezer',
    category: 'music',
    aliases: ['ดีเซอร์'],
    regions: ['Global', 'ทั่วโลก', 'France', 'ฝรั่งเศส'],
    domains: ['deezer.com'],
    matches: [],
    sampleUrl: 'https://deezer.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'deezer.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 34.0,
      top: 34.0,
      width: 172.0,
      height: 172.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'patreon',
    name: 'Patreon',
    category: 'creator',
    aliases: ['แพทรีออน'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['patreon.com'],
    matches: [],
    sampleUrl: 'https://patreon.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'patreon.png',
      sourceWidth: 256.0,
      sourceHeight: 256.0,
      left: 0.0,
      top: 0.0,
      width: 256.0,
      height: 256.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'ko_fi',
    name: 'Ko-fi',
    category: 'creator',
    aliases: ['KoFi', 'โคไฟ'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['ko-fi.com'],
    matches: [],
    sampleUrl: 'https://ko-fi.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'ko_fi.png',
      sourceWidth: 256.0,
      sourceHeight: 256.0,
      left: 0.0,
      top: 0.0,
      width: 256.0,
      height: 256.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'buy_me_a_coffee',
    name: 'Buy Me a Coffee',
    category: 'creator',
    aliases: ['BMAC', 'บายมีอะคอฟฟี่'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['buymeacoffee.com'],
    matches: [],
    sampleUrl: 'https://buymeacoffee.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'buy_me_a_coffee.png',
      sourceWidth: 48.0,
      sourceHeight: 48.0,
      left: 0.0,
      top: 0.0,
      width: 48.0,
      height: 48.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'substack',
    name: 'Substack',
    category: 'creator',
    aliases: ['ซับสแต็ก'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['substack.com'],
    matches: [],
    sampleUrl: 'https://substack.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'substack.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'medium',
    name: 'Medium',
    category: 'creator',
    aliases: ['มีเดียม'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['medium.com'],
    matches: [],
    sampleUrl: 'https://medium.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'medium.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'wordpress',
    name: 'WordPress',
    category: 'creator',
    aliases: ['เวิร์ดเพรส'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['wordpress.com', 'wordpress.org'],
    matches: [],
    sampleUrl: 'https://wordpress.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'wordpress.png',
      sourceWidth: 114.0,
      sourceHeight: 114.0,
      left: 0.0,
      top: 0.0,
      width: 114.0,
      height: 114.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'tumblr',
    name: 'Tumblr',
    category: 'social',
    aliases: ['ทัมเบลอร์'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['tumblr.com'],
    matches: [],
    sampleUrl: 'https://tumblr.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'tumblr.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'amazon',
    name: 'Amazon',
    category: 'shopping',
    aliases: ['อะเมซอน'],
    regions: ['Global', 'ทั่วโลก', 'US', 'United States', 'สหรัฐอเมริกา'],
    domains: ['amazon.com', 'amzn.to'],
    matches: [],
    sampleUrl: 'https://amazon.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'amazon.png',
      sourceWidth: 180.0,
      sourceHeight: 180.0,
      left: 0.0,
      top: 0.0,
      width: 180.0,
      height: 180.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'aliexpress',
    name: 'AliExpress',
    category: 'shopping',
    aliases: ['อาลีเอ็กซ์เพรส'],
    regions: ['Global', 'ทั่วโลก', 'China', 'จีน'],
    domains: ['aliexpress.com'],
    matches: [],
    sampleUrl: 'https://aliexpress.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'aliexpress.png',
      sourceWidth: 400.0,
      sourceHeight: 400.0,
      left: 0.0,
      top: 0.0,
      width: 400.0,
      height: 400.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'ebay',
    name: 'eBay',
    category: 'shopping',
    aliases: ['อีเบย์'],
    regions: ['Global', 'ทั่วโลก', 'US', 'United States', 'สหรัฐอเมริกา'],
    domains: ['ebay.com', 'ebay.co.uk'],
    matches: [],
    sampleUrl: 'https://ebay.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'ebay.png',
      sourceWidth: 512.0,
      sourceHeight: 219.0,
      left: 50.0,
      top: 31.0,
      width: 382.0,
      height: 157.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'etsy',
    name: 'Etsy',
    category: 'shopping',
    aliases: ['เอ็ตซี'],
    regions: ['Global', 'ทั่วโลก', 'US', 'United States', 'สหรัฐอเมริกา'],
    domains: ['etsy.com'],
    matches: [],
    sampleUrl: 'https://etsy.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'etsy.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'walmart',
    name: 'Walmart',
    category: 'shopping',
    aliases: ['วอลมาร์ต'],
    regions: ['Global', 'ทั่วโลก', 'US', 'United States', 'สหรัฐอเมริกา'],
    domains: ['walmart.com'],
    matches: [],
    sampleUrl: 'https://walmart.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'walmart.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 13.0,
      top: 0.0,
      width: 214.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'temu',
    name: 'Temu',
    category: 'shopping',
    aliases: ['ทีมู', 'เทมู'],
    regions: ['Global', 'ทั่วโลก', 'China', 'จีน'],
    domains: ['temu.com'],
    matches: [],
    sampleUrl: 'https://temu.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'temu.png',
      sourceWidth: 400.0,
      sourceHeight: 400.0,
      left: 0.0,
      top: 0.0,
      width: 400.0,
      height: 400.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'mercado_libre',
    name: 'Mercado Libre',
    category: 'shopping',
    aliases: ['Mercado Livre', 'เมร์กาโดลิเบร'],
    regions: ['Global', 'ทั่วโลก', 'Latin America', 'ลาตินอเมริกา', 'Brazil', 'บราซิล', 'Mexico', 'เม็กซิโก', 'Argentina', 'อาร์เจนตินา'],
    domains: ['mercadolibre.com', 'mercadolibre.com.ar', 'mercadolibre.com.mx', 'mercadolivre.com.br'],
    matches: [],
    sampleUrl: 'https://mercadolibre.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'mercado_libre.png',
      sourceWidth: 60.0,
      sourceHeight: 60.0,
      left: 0.0,
      top: 0.0,
      width: 60.0,
      height: 60.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'ozon',
    name: 'Ozon',
    category: 'shopping',
    aliases: ['Озон', 'โอโซน'],
    regions: ['Global', 'ทั่วโลก', 'Russia', 'รัสเซีย'],
    domains: ['ozon.ru'],
    matches: [],
    sampleUrl: 'https://ozon.ru/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'ozon.png',
      sourceWidth: 400.0,
      sourceHeight: 400.0,
      left: 0.0,
      top: 0.0,
      width: 400.0,
      height: 400.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'wildberries',
    name: 'Wildberries',
    category: 'shopping',
    aliases: ['Вайлдберриз', 'ไวลด์เบอร์รีส์'],
    regions: ['Global', 'ทั่วโลก', 'Russia', 'รัสเซีย'],
    domains: ['wildberries.ru'],
    matches: [],
    sampleUrl: 'https://wildberries.ru/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'wildberries.png',
      sourceWidth: 48.0,
      sourceHeight: 48.0,
      left: 0.0,
      top: 0.0,
      width: 48.0,
      height: 48.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'vk',
    name: 'VK',
    category: 'social',
    aliases: ['ВКонтакте', 'VKontakte', 'วีเค'],
    regions: ['Global', 'ทั่วโลก', 'Russia', 'รัสเซีย'],
    domains: ['vk.com'],
    matches: [],
    sampleUrl: 'https://vk.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'vk.png',
      sourceWidth: 512.0,
      sourceHeight: 512.0,
      left: 0.0,
      top: 0.0,
      width: 512.0,
      height: 512.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'ok',
    name: 'OK',
    category: 'social',
    aliases: ['Одноклассники', 'Odnoklassniki'],
    regions: ['Global', 'ทั่วโลก', 'Russia', 'รัสเซีย'],
    domains: ['ok.ru'],
    matches: [],
    sampleUrl: 'https://ok.ru/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'ok.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'airbnb',
    name: 'Airbnb',
    category: 'travel',
    aliases: ['แอร์บีเอ็นบี'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['airbnb.com'],
    matches: [],
    sampleUrl: 'https://airbnb.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'airbnb.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'booking',
    name: 'Booking.com',
    category: 'travel',
    aliases: ['บุ๊กกิ้ง'],
    regions: ['Global', 'ทั่วโลก', 'Europe', 'ยุโรป'],
    domains: ['booking.com'],
    matches: [],
    sampleUrl: 'https://booking.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'booking.png',
      sourceWidth: 256.0,
      sourceHeight: 256.0,
      left: 3.0,
      top: 3.0,
      width: 253.0,
      height: 253.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'tripadvisor',
    name: 'Tripadvisor',
    category: 'travel',
    aliases: ['ทริปแอดไวเซอร์'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['tripadvisor.com'],
    matches: [],
    sampleUrl: 'https://tripadvisor.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'tripadvisor.png',
      sourceWidth: 320.0,
      sourceHeight: 320.0,
      left: 28.0,
      top: 76.0,
      width: 263.0,
      height: 169.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'github',
    name: 'GitHub',
    category: 'tools',
    aliases: ['กิตฮับ'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['github.com'],
    matches: [],
    sampleUrl: 'https://github.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'github.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 235.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'linktree',
    name: 'Linktree',
    category: 'creator',
    aliases: ['ลิงก์ทรี'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['linktr.ee'],
    matches: [],
    sampleUrl: 'https://linktr.ee/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'linktree.png',
      sourceWidth: 256.0,
      sourceHeight: 256.0,
      left: 0.0,
      top: 0.0,
      width: 256.0,
      height: 256.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'beacons',
    name: 'Beacons',
    category: 'creator',
    aliases: ['บีคอนส์'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['beacons.ai'],
    matches: [],
    sampleUrl: 'https://beacons.ai/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'beacons.png',
      sourceWidth: 48.0,
      sourceHeight: 48.0,
      left: 0.0,
      top: 0.0,
      width: 48.0,
      height: 48.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'google_drive',
    name: 'Google Drive',
    category: 'tools',
    aliases: ['กูเกิลไดรฟ์'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['drive.google.com'],
    matches: [],
    sampleUrl: 'https://drive.google.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'google_drive.png',
      sourceWidth: 128.0,
      sourceHeight: 128.0,
      left: 8.0,
      top: 9.0,
      width: 112.0,
      height: 103.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'dropbox',
    name: 'Dropbox',
    category: 'tools',
    aliases: ['ดรอปบ็อกซ์'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['dropbox.com', 'db.tt'],
    matches: [],
    sampleUrl: 'https://dropbox.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'dropbox.png',
      sourceWidth: 240.0,
      sourceHeight: 240.0,
      left: 0.0,
      top: 0.0,
      width: 240.0,
      height: 240.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'notion',
    name: 'Notion',
    category: 'tools',
    aliases: ['โนชัน'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['notion.so', 'notion.site', 'notion.com'],
    matches: [],
    sampleUrl: 'https://notion.so/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'notion.png',
      sourceWidth: 512.0,
      sourceHeight: 512.0,
      left: 0.0,
      top: 0.0,
      width: 512.0,
      height: 512.0,
    ),
  ),
  ProfilePlatformDefinition(
    id: 'canva',
    name: 'Canva',
    category: 'tools',
    aliases: ['แคนวา'],
    regions: ['Global', 'ทั่วโลก'],
    domains: ['canva.com'],
    matches: [],
    sampleUrl: 'https://canva.com/postdee-demo',
    asset: ProfilePlatformArtwork(
      file: 'canva.png',
      sourceWidth: 400.0,
      sourceHeight: 400.0,
      left: 0.0,
      top: 0.0,
      width: 400.0,
      height: 400.0,
    ),
  ),
];

const profilePlatformIds = <String>{
  'youtube',
  'shopee',
  'lazada',
  'line',
  'tiktok',
  'instagram',
  'facebook',
  'messenger',
  'whatsapp',
  'google_maps',
  'wechat',
  'qq',
  'weibo',
  'douyin',
  'bilibili',
  'xiaohongshu',
  'kuaishou',
  'taobao',
  'tmall',
  'jd',
  'pinduoduo',
  'alipay',
  'baidu',
  'zhihu',
  'douban',
  'youku',
  'dingtalk',
  'netease_music',
  'meituan',
  'eleme',
  'trip_com',
  'kakao_talk',
  'naver',
  'coupang',
  'band',
  'rakuten',
  'mercari',
  'yahoo_japan',
  'paypay',
  'niconico',
  'pixiv',
  'sharechat',
  'moj',
  'flipkart',
  'meesho',
  'zalo',
  'tokopedia',
  'tiki',
  'traveloka',
  'grab',
  'gojek',
  'carousell',
  'daraz',
  'x',
  'threads',
  'bluesky',
  'mastodon',
  'snapchat',
  'pinterest',
  'linkedin',
  'reddit',
  'telegram',
  'signal',
  'viber',
  'discord',
  'twitch',
  'kick',
  'spotify',
  'apple_music',
  'soundcloud',
  'bandcamp',
  'deezer',
  'patreon',
  'ko_fi',
  'buy_me_a_coffee',
  'substack',
  'medium',
  'wordpress',
  'tumblr',
  'amazon',
  'aliexpress',
  'ebay',
  'etsy',
  'walmart',
  'temu',
  'mercado_libre',
  'ozon',
  'wildberries',
  'vk',
  'ok',
  'airbnb',
  'booking',
  'tripadvisor',
  'github',
  'linktree',
  'beacons',
  'google_drive',
  'dropbox',
  'notion',
  'canva',
};

const profilePlatformNames = <String, String>{
  'youtube': 'YouTube',
  'shopee': 'Shopee',
  'lazada': 'Lazada',
  'line': 'LINE',
  'tiktok': 'TikTok',
  'instagram': 'Instagram',
  'facebook': 'Facebook',
  'messenger': 'Messenger',
  'whatsapp': 'WhatsApp',
  'google_maps': 'Google Maps',
  'wechat': 'WeChat',
  'qq': 'QQ',
  'weibo': 'Weibo',
  'douyin': 'Douyin',
  'bilibili': 'Bilibili',
  'xiaohongshu': 'Xiaohongshu',
  'kuaishou': 'Kuaishou',
  'taobao': 'Taobao',
  'tmall': 'Tmall',
  'jd': 'JD.com',
  'pinduoduo': 'Pinduoduo',
  'alipay': 'Alipay',
  'baidu': 'Baidu',
  'zhihu': 'Zhihu',
  'douban': 'Douban',
  'youku': 'Youku',
  'dingtalk': 'DingTalk',
  'netease_music': 'NetEase Cloud Music',
  'meituan': 'Meituan',
  'eleme': 'Taobao Instant Commerce',
  'trip_com': 'Trip.com',
  'kakao_talk': 'KakaoTalk',
  'naver': 'NAVER',
  'coupang': 'Coupang',
  'band': 'BAND',
  'rakuten': 'Rakuten',
  'mercari': 'Mercari',
  'yahoo_japan': 'Yahoo! Japan',
  'paypay': 'PayPay',
  'niconico': 'Niconico',
  'pixiv': 'pixiv',
  'sharechat': 'ShareChat',
  'moj': 'Moj',
  'flipkart': 'Flipkart',
  'meesho': 'Meesho',
  'zalo': 'Zalo',
  'tokopedia': 'Tokopedia',
  'tiki': 'Tiki',
  'traveloka': 'Traveloka',
  'grab': 'Grab',
  'gojek': 'Gojek',
  'carousell': 'Carousell',
  'daraz': 'Daraz',
  'x': 'X',
  'threads': 'Threads',
  'bluesky': 'Bluesky',
  'mastodon': 'Mastodon',
  'snapchat': 'Snapchat',
  'pinterest': 'Pinterest',
  'linkedin': 'LinkedIn',
  'reddit': 'Reddit',
  'telegram': 'Telegram',
  'signal': 'Signal',
  'viber': 'Viber',
  'discord': 'Discord',
  'twitch': 'Twitch',
  'kick': 'Kick',
  'spotify': 'Spotify',
  'apple_music': 'Apple Music',
  'soundcloud': 'SoundCloud',
  'bandcamp': 'Bandcamp',
  'deezer': 'Deezer',
  'patreon': 'Patreon',
  'ko_fi': 'Ko-fi',
  'buy_me_a_coffee': 'Buy Me a Coffee',
  'substack': 'Substack',
  'medium': 'Medium',
  'wordpress': 'WordPress',
  'tumblr': 'Tumblr',
  'amazon': 'Amazon',
  'aliexpress': 'AliExpress',
  'ebay': 'eBay',
  'etsy': 'Etsy',
  'walmart': 'Walmart',
  'temu': 'Temu',
  'mercado_libre': 'Mercado Libre',
  'ozon': 'Ozon',
  'wildberries': 'Wildberries',
  'vk': 'VK',
  'ok': 'OK',
  'airbnb': 'Airbnb',
  'booking': 'Booking.com',
  'tripadvisor': 'Tripadvisor',
  'github': 'GitHub',
  'linktree': 'Linktree',
  'beacons': 'Beacons',
  'google_drive': 'Google Drive',
  'dropbox': 'Dropbox',
  'notion': 'Notion',
  'canva': 'Canva',
};

final profilePlatformsById = Map<String, ProfilePlatformDefinition>.unmodifiable({
  for (final platform in profilePlatformCatalog) platform.id: platform,
});
